### PR TITLE
Added support for DPT 24.* and DPT 28.*.

### PR DESCRIPTION
**Pull request by ab-tools**

### CODE REVIEW

**Comment by ab-tools** [comment]
Another question, noticed while working on this:
What is the reason that `signed8FromPayload` is used for 14 byte strings here instead of `unsigned8FromPayload`?
https://github.com/OpenKNX/knx/blob/v1/src/knx/dptconvert.cpp#L524

This is even more strange as `unsigned8ToPayload` is used for the opposite conversion direction:
https://github.com/OpenKNX/knx/blob/v1/src/knx/dptconvert.cpp#L1196

Is there a specific reason for this or a bug that should be fixed?

**Comment by Ing-Dom** [comment]
please change your PR to merge into v1dev instead of v1

**Comment by ab-tools** [comment]
Sure, done.

**Comment by Ing-Dom** [comment]
thx. and please merge the latest v1dev to your feature branch then the checks should all be ok

**Comment by ab-tools** [comment]
Done as well.

**Comment by ab-tools** [comment]
Will create new PR, when ready - as discussed in Slack.

**Pull request closed without merging**
