### PR TITLE
Add function to group object to send a value only if it was changed.

### PR DESCRIPTION
**Pull request by mgeramb**
Adds a function to set and send a value only if it was changed. Similar to the function valueNoSentCompare the function is named valueCompare.

### CODE REVIEW

**Comment by Ing-Dom** [comment]
please change your PR to merge into v1dev instead of v1

**Comment by mgeramb** [comment]
Done

**Comment by Ing-Dom** [comment]
please merge v1dev into your branch so the checks are all green.
Then I'll merge this

**Comment by mgeramb** [comment]
I have done a rebase on v1dev

**Pull request merged**
